#!/bin/env fish

java -jar /usr/local/lib/antlr-4.8-complete.jar resources/grammars/Omnilisp.g4 \
      -o src/java/omnilisp/parsers  \
      -package Omnilisp.parsers \
      -visitor -message-format gnu
