/* Generated by OmniLisp Compiler */
/* ASAP Memory Management - Compile-Time Free Injection */

#include "../runtime/include/omni.h"

#define NIL mk_pair(NULL, NULL)
#define NOTHING mk_nothing()
#define omni_print(o) prim_print(o)
#define car(o) obj_car(o)
#define cdr(o) obj_cdr(o)
#define mk_cell(a, b) mk_pair(a, b)
#define prim_cons(a, b) mk_pair(a, b)

int main(void) {
    {
        Obj* _result = ({
            Obj* o_x = mk_int(1);
            (omni_print(o_x), NOTHING);
        });
        omni_print(_result);
        printf("\n");
        free_obj(_result);
    }
    return 0;
}
