#!/usr/bin/env python3

from __future__ import annotations

import argparse
import struct
import zlib
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = REPO_ROOT / "src/entry_language_reference_payload_source.md"
OUTPUT_GZIP_PATH = REPO_ROOT / "src/entry_language_reference_payload.gz"
OUTPUT_C3_PATH = REPO_ROOT / "src/entry_language_reference_payload.c3"

GZIP_HEADER = b"\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\x03"


def gzip_deterministic(data: bytes) -> bytes:
    compressor = zlib.compressobj(
        level=9,
        method=zlib.DEFLATED,
        wbits=-zlib.MAX_WBITS,
    )
    body = compressor.compress(data) + compressor.flush()
    trailer = struct.pack("<II", zlib.crc32(data) & 0xFFFFFFFF, len(data) & 0xFFFFFFFF)
    return GZIP_HEADER + body + trailer


def render_c3(text_len: int) -> str:
    return f"""module main;

// Generated by scripts/generate_language_reference_payload.py
// from src/entry_language_reference_payload_source.md.
const usz OMNI_LANGUAGE_REF_TEXT_LEN = {text_len};
const char[] OMNI_LANGUAGE_REF_GZIP = $embed(\"entry_language_reference_payload.gz\");
"""


def write_if_changed(path: Path, data: bytes) -> bool:
    if path.exists() and path.read_bytes() == data:
        return False
    path.write_bytes(data)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate deterministic embedded language-reference payload artifacts."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated artifacts are up to date without rewriting them.",
    )
    args = parser.parse_args()

    source_bytes = SOURCE_PATH.read_bytes()
    gzip_bytes = gzip_deterministic(source_bytes)
    c3_bytes = render_c3(len(source_bytes)).encode("utf-8")

    if args.check:
        gzip_ok = OUTPUT_GZIP_PATH.exists() and OUTPUT_GZIP_PATH.read_bytes() == gzip_bytes
        c3_ok = OUTPUT_C3_PATH.exists() and OUTPUT_C3_PATH.read_bytes() == c3_bytes
        return 0 if gzip_ok and c3_ok else 1

    write_if_changed(OUTPUT_GZIP_PATH, gzip_bytes)
    write_if_changed(OUTPUT_C3_PATH, c3_bytes)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
