local defaults = {
  repo_root = nil,
  cmd = { "omni", "--repl", "--json" },
  repl = {
    mode = "json",
    discovery = {
      enabled = true,
      host = "127.0.0.1",
      port_file = ".omni-repl-port",
    },
  },
  eval = {
    mode = "json",
    cmd = { "omni", "--eval", "--json" },
    fallback_to_repl = true,
    annotations = {
      enabled = false,
      max_length = 160,
      labels = {
        form = true,
        root = true,
        call = true,
        block = true,
        declaration = true,
        line = true,
      },
      hl = {
        ok = "DiagnosticOk",
        error = "DiagnosticError",
      },
    },
  },
  output = {
    name = "Omni REPL",
    split = "botright 12split",
    auto_scroll = true,
    pretty_values = true,
    pretty_width = 72,
    pretty_indent = 2,
  },
  auto_start = true,
  lsp = {
    auto_setup = false,
    enable = true,
    cmd = nil,
    server_path = nil,
    repo_root = nil,
    root_markers = { "omni.toml", "project.json", ".git" },
    highlights = {
      auto_refresh = false,
      refresh_events = { "CursorHold", "CursorHoldI" },
      clear_events = { "CursorMoved", "InsertEnter", "BufLeave" },
    },
    codelens = {
      auto_refresh = false,
      events = { "BufEnter", "InsertLeave" },
    },
    pull_diagnostics = {
      auto_refresh = false,
      events = { "BufEnter", "InsertLeave" },
      auto_open = false,
      auto_notify_empty = false,
      workspace_auto_refresh = false,
      workspace_events = { "BufWritePost" },
      workspace_auto_open = false,
      workspace_auto_notify_empty = false,
      all_auto_refresh = false,
      all_events = { "BufEnter", "BufWritePost" },
      all_auto_open = false,
      all_auto_notify_empty = false,
    },
    mappings = true,
    keys = {
      hover = "K",
      definition = "gd",
      definition_list = "<localleader>lg",
      declaration = "gD",
      declaration_list = "<localleader>lG",
      implementation = "gi",
      implementation_list = "<localleader>lI",
      type_definition = "<localleader>lt",
      type_definition_list = "<localleader>lT",
      incoming_calls = "<localleader>lC",
      outgoing_calls = "<localleader>lc",
      references = "grr",
      references_list = "<localleader>lR",
      rename = "<localleader>lr",
      code_action = "<localleader>la",
      format = "<localleader>lf",
      signature_help = "<localleader>ls",
      document_symbols = "<localleader>lq",
      workspace_symbols = "<localleader>lQ",
      open_link = "<localleader>lo",
      document_links = "<localleader>lO",
      next_link = "]o",
      prev_link = "[o",
      highlight = "<localleader>lh",
      clear_highlights = "<localleader>lH",
      diagnostics = "<localleader>ld",
      document_diagnostics = "<localleader>lp",
      workspace_diagnostics = "<localleader>lP",
      all_diagnostics = "<localleader>lA",
      diagnostic_next = "]d",
      diagnostic_prev = "[d",
      code_lens_refresh = "<localleader>ll",
      code_lens_run = "<localleader>lL",
      inlay_hints = "<localleader>li",
      folds = "<localleader>lz",
      expand_selection = "<localleader>lv",
    },
  },
  formatter = {
    name = "omni_fmt",
    cmd = { "omni", "--fmt", "--write", "$FILENAME" },
    cwd = nil,
  },
  treesitter = {
    register = true,
    append_runtimepath = true,
    grammar_dir = nil,
    repo_root = nil,
  },
  textobjects = {
    enabled = true,
    keys = {
      form_outer = "af",
      form_inner = "if",
      root_outer = "ar",
      root_inner = "ir",
      declaration_outer = "ad",
      declaration_inner = "id",
      call_outer = "ac",
      call_inner = "ic",
      block_outer = "aB",
      block_inner = "iB",
    },
  },
  mappings = true,
  keys = {
    start = "<localleader>rs",
    restart = "<localleader>rr",
    open = "<localleader>ro",
    clear = "<localleader>rc",
    select_decl = "<localleader>sd",
    select_call = "<localleader>sc",
    select_block = "<localleader>sb",
    select_form = "<localleader>sf",
    select_root = "<localleader>sr",
    eval_decl = "<localleader>ed",
    eval_call = "<localleader>ec",
    eval_block = "<localleader>ep",
    eval_operator = "<localleader>eo",
    eval_form = "<localleader>ef",
    eval_root = "<localleader>er",
    eval_line = "<localleader>el",
    eval_selection = "<localleader>es",
    eval_buffer = "<localleader>eb",
  },
}

return defaults
