#include <stddef.h>
#include <stdint.h>

const uint32_t omni_tensor_vulkan_general_eigen_f32_spv[] = {
#include "tensor_vulkan_general_eigen_f32_spv_part_000.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_001.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_002.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_003.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_004.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_005.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_006.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_007.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_008.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_009.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_010.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_011.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_012.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_013.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_014.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_015.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_016.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_017.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_018.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_019.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_020.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_021.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_022.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_023.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_024.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_025.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_026.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_027.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_028.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_029.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_030.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_031.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_032.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_033.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_034.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_035.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_036.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_037.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_038.inc"
#include "tensor_vulkan_general_eigen_f32_spv_part_039.inc"
};

const size_t omni_tensor_vulkan_general_eigen_f32_spv_size = sizeof(omni_tensor_vulkan_general_eigen_f32_spv);
